import ToasterContext from './context/ToasterContext'
import './globals.css'
import { Assistant } from 'next/font/google'

const font = Assistant({ subsets: ['latin'] })

export const metadata = {
  title: 'chat',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ToasterContext />
        {children}
      </body>
    </html>
  )
}
